# Generated by Django 4.2 on 2025-01-19 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_code', models.CharField(help_text='Unique code for the syllabus unit', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Title of the syllabus unit', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description/sub-topics of the unit', null=True)),
                ('semester', models.ForeignKey(help_text='Semester in which the syllabus unit is taught (e.g., 1, 2, etc.)', on_delete=django.db.models.deletion.CASCADE, to='courses.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_units', to='subjects.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
