# Generated by Django 4.2 on 2025-01-19 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('BTECH', 'Bachelor of Technology in Computer Science'), ('MTECH', 'Master of Technology in Computer Science'), ('BCA', 'Bachelor of Computer Applications'), ('MCA', 'Master of Computer Applications'), ('DIPLOMA_CSE', 'Diploma in Computer Science and Engineering'), ('PHD_CS', 'Doctor of Philosophy in Computer Science'), ('BTECH', 'Bachelor of Technology in Mechanical Engineering'), ('MTECH', 'Master of Technology in Mechanical Engineering'), ('DIPLOMA_MECH', 'Diploma in Mechanical Engineering'), ('PHD_MECH', 'Doctor of Philosophy in Mechanical Engineering'), ('BTECH', 'Bachelor of Technology in Civil Engineering'), ('MTECH', 'Master of Technology in Civil Engineering'), ('DIPLOMA_CIVIL', 'Diploma in Civil Engineering'), ('PHD_CIVIL', 'Doctor of Philosophy in Civil Engineering'), ('BTECH', 'Bachelor of Technology in Electronics and Communication'), ('MTECH', 'Master of Technology in Electronics and Communication'), ('DIPLOMA_ECE', 'Diploma in Electronics and Communication'), ('PHD_ECE', 'Doctor of Philosophy in Electronics and Communication'), ('BTECH', 'Bachelor of Technology in Information Technology'), ('MTECH', 'Master of Technology in Information Technology'), ('BSC_IT', 'Bachelor of Science in Information Technology'), ('MSC_IT', 'Master of Science in Information Technology'), ('DIPLOMA_IT', 'Diploma in Information Technology'), ('PHD_IT', 'Doctor of Philosophy in Information Technology'), ('BTECH', 'Bachelor of Technology in Electrical Engineering'), ('MTECH', 'Master of Technology in Electrical Engineering'), ('DIPLOMA_EE', 'Diploma in Electrical Engineering'), ('PHD_EE', 'Doctor of Philosophy in Electrical Engineering'), ('BSC_MATH', 'Bachelor of Science in Mathematics'), ('MSC_MATH', 'Master of Science in Mathematics'), ('PHD_MATH', 'Doctor of Philosophy in Mathematics'), ('BSC_PHYS', 'Bachelor of Science in Physics'), ('MSC_PHYS', 'Master of Science in Physics'), ('PHD_PHYS', 'Doctor of Philosophy in Physics'), ('BSC_CHEM', 'Bachelor of Science in Chemistry'), ('MSC_CHEM', 'Master of Science in Chemistry'), ('PHD_CHEM', 'Doctor of Philosophy in Chemistry'), ('BTECH', 'Bachelor of Technology in Biotechnology'), ('MTECH', 'Master of Technology in Biotechnology'), ('BSC_BIOTECH', 'Bachelor of Science in Biotechnology'), ('MSC_BIOTECH', 'Master of Science in Biotechnology'), ('PHD_BIOTECH', 'Doctor of Philosophy in Biotechnology')], max_length=20, unique=True)),
                ('duration_years', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this course is active or not.')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='departments.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True, help_text='Whether this semester is active or not.')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='courses.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSemesterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='The academic year (e.g., 2024)')),
                ('date_changed', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True, help_text='Indicates if this is the current semester for the student')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_history', to='courses.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_history', to='accounts.student')),
            ],
            options={
                'verbose_name_plural': 'Student Semester Histories',
                'ordering': ['-date_changed'],
            },
        ),
    ]
