# Generated by Django 4.2 on 2025-01-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('IT', 'Information Technology'), ('EE', 'Electrical Engineering'), ('MATH', 'Mathematics'), ('PHYS', 'Physics'), ('CHEM', 'Chemistry'), ('BIOTECH', 'Biotechnology'), ('BBA', 'Business Administration'), ('COM', 'Commerce'), ('ENG', 'English'), ('ECO', 'Economics'), ('PSY', 'Psychology')], max_length=20, unique=True)),
                ('established_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this department is active or not.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
