# Generated by Django 4.2 on 2025-01-19 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syllabus', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture_code', models.CharField(help_text='Unique code for the lecture', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Title of the lecture', max_length=255)),
                ('date', models.DateField(help_text='Date of the lecture')),
                ('start_time', models.TimeField(help_text='Start time of the lecture')),
                ('end_time', models.TimeField(help_text='End time of the lecture')),
                ('location', models.CharField(help_text='Location or classroom for the lecture', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the lecture is active or canceled')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='accounts.teacher')),
                ('syllabus_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='syllabus.syllabusunit')),
            ],
            options={
                'verbose_name_plural': 'Lectures',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_present', models.BooleanField(default=False, help_text='Indicates whether the student was present or absent.')),
                ('attendance_date', models.DateField(auto_now_add=True, help_text='The date the attendance was recorded')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='lectures.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.student')),
            ],
            options={
                'unique_together': {('lecture', 'student')},
            },
        ),
    ]
